#!/usr/bin/env python3
"""List TaskBots and summarize a workflow. No tokens printed.

Replacement for session scratch `zw_inspect_demos.py`. Pass a bot id or
a name prefix — do not bake demo ids into this file.

    python zw_inspect.py
    python zw_inspect.py --prefix Demo
    python zw_inspect.py --bot 12345
    python zw_inspect.py --name "Demo - X Feed Scraper"
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from zw_api import (  # noqa: E402
    TokenError,
    find_connector,
    get_workflow,
    iter_connectors,
    list_data_groups,
    normalize_data_groups,
    summarize_workflow,
    table_count,
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Inspect ZeroWork bots (tokens from env).")
    parser.add_argument("--bot", help="connector id")
    parser.add_argument("--name", help="exact TaskBot name")
    parser.add_argument("--prefix", help="print bots whose name starts with this")
    args = parser.parse_args(argv)

    bots = list(iter_connectors())
    if args.prefix:
        pref = args.prefix.lower()
        bots = [b for b in bots if str(b.get("name") or "").lower().startswith(pref)]
    listing = [{"id": b.get("id"), "name": b.get("name")} for b in bots]
    print(json.dumps({"bots": listing}, indent=2))

    target = args.bot
    if not target and args.name:
        hit = find_connector(args.name)
        if not hit:
            print("no bot named %r" % args.name, file=sys.stderr)
            return 1
        target = hit.get("id")
    if not target:
        return 0

    status, wf = get_workflow(target)
    print(json.dumps({"bot": target, "workflow_status": status, **summarize_workflow(wf)}, indent=2))
    stg, groups = list_data_groups(target)
    rows = []
    for group in normalize_data_groups(groups):
        gid = group.get("id")
        count_body = None
        if gid is not None:
            _stc, count_body = table_count(gid)
        rows.append(
            {
                "id": gid,
                "name": group.get("name"),
                "type": group.get("type"),
                "auto": group.get("is_autogenerated"),
                "item_count": count_body,
            }
        )
    print(json.dumps({"tables_status": stg, "tables": rows}, indent=2))
    return 0 if status == 200 else 1


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except TokenError as exc:
        print(str(exc), file=sys.stderr)
        raise SystemExit(2)
